### ISSUE TITLE
How to check for support v4 in android SDK?

### ISSUE THREAD

**Issue by rajeshvishnani** [freshdesk/mobihelp-phonegap#3]
Hi, 

I have successfully integrated this plugin, but here is little problem, i can see the solutions in iOS but not in android, then i saw some requirements about Android, i have rest of 2 done, i dont know how to check support v4 in android sdk? please help me.

Regards
Rajesh

**Comment by SatheeshJM** [comment]
Hey Rajesh, 

If you have appcompat v7 installed, appcompat v4 will automatically be added as a dependancy to the project.  
So that should not be a problem. 
Just make sure you have  'Android support repository installed.. 
https://developer.android.com/tools/support-library/setup.html

And also, note that you have to create a separate app credentials(appId and appSecret) for android in freshdesk's mobihelp admin section..

**Comment by rajeshvishnani** [comment]
Ok and can you please confirm once again about how to install appcompat v7, may be i am doing something wrong in installing that.

**Comment by SatheeshJM** [comment]
As we'd discussed previously(https://github.com/freshdesk/mobihelp-phonegap/issues/2),  you can find instructions for installing appcompat in this link : https://developer.android.com/tools/support-library/setup.html

**Comment by rajeshvishnani** [comment]
Ok then i have already added it, still not working.
