### ISSUE TITLE
The name of my app changes to FreshdeskSDK

### ISSUE THREAD

**Issue by jonathancod** [freshdesk/mobihelp-phonegap#6]
Is that supose to happen?

System information:

Cordova CLI: 5.3.1
Gulp version:  CLI version 3.9.0
Gulp local:  
Ionic Version: 1.1.1
Ionic CLI Version: 1.7.8
Ionic App Lib Version: 0.6.4
OS: Windows 8.1
Node Version: v4.2.1

Plugin list:
com.phonegap.plugins.PushPlugin 2.5.0 "PushPlugin"
cordova-plugin-console 1.0.1 "Console"
cordova-plugin-device 1.0.1 "Device"
cordova-plugin-freshdesk-mobihelp 1.1.0 "Mobihelp Plugin for Phonegap"
cordova-plugin-splashscreen 2.1.0 "Splashscreen"
cordova-plugin-statusbar 1.0.1 "StatusBar"
cordova-plugin-whitelist 1.0.0 "Whitelist"
ionic-plugin-keyboard 1.0.8 "Keyboard"

After i install this plugin on my project go a device to test it and the app name has changed to FreshdeskSDK.

This is on android. Not tested in IOS

**Comment by zanemcca** [comment]
I am having this issue as well in production. This is a serious bug as it destroys app branding.

**Comment by ripcurlx** [comment]
+1

**Comment by zanemcca** [comment]
Hey guys this turned out to be an issue with language support.
So if you do not have a language file for each of the languages mobihelp uses then android will use their language file. This file will change your name.

My dirty but simple [solution](https://github.com/instanews/mobihelp-phonegap) was to remove all language files I do not support myself.

**Comment by rsquare2014** [comment]
We have fixed this in the latest version of our SDK, please update.
